version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - m50
  labels:
  - dependencies
  ignore:
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.3.1
    - 6.3.3
  - dependency-name: "@sentry/react"
    versions:
    - 6.3.1
    - 6.3.3
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: "@tailwindcss/jit"
    versions:
    - 0.1.18
  - dependency-name: msw
    versions:
    - 0.28.1
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
  - dependency-name: postcss
    versions:
    - 8.2.9
