title: Marisa Clardy
author:
  name: Marisa Clardy
  email: marisa@clardy.eu
description: >-
  The website for Marisa Clardy.
baseurl: ""
url: "https://clardy.eu"

social:
  twitter: MarisaCodes
  github:  m50
  instagram: marisaclardy1
  devto: m50
  gitlab:
    - username: MarisaCodes
      instance: gitlab.com

plugins:
  - jekyll-seo-tag
