title: Marisa Clardy
author:
  name: © Marisa Clardy 2020
  email: marisa@clardy.eu
description: >-
  I am Marisa Clardy, and this is my site, where I share information about
  myself, what I'm working on, and cool things I have discovered.
baseurl: ""
url: "https://clardy.eu"

social:
  twitter: MarisaCodes
  github:  m50
  instagram: marisaclardy1
  devto: m50
  gitlab:
    - username: MarisaCodes
      instance: gitlab.com

plugins:
  - jekyll-seo-tag
