[build]
  command = "yarn build"
  publish = "out"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
