name: Validate
on:
  push:
    branches: [ trunk ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: List, test, build
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - name: Install Modules
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Lint types
        run: bun run lint:types
      - name: Run Tests
        run: bun test
      - name: Built
        run: bun run build
